application: hundred-best-books
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: web.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
